### ISSUE TITLE
psc: command not found after a fresh install

### ISSUE THREAD

**Issue by SiegfriedEhret** [ThomasCrevoisier/psvm-js#9]
I `psvm install v0.8.5` which worked fine.

When I `psvm current`, I have the following output:

```
Unhandled rejection Error: Command failed: psc --version
/bin/sh: psc: command not found

   at ChildProcess.exithandler (child_process.js:202:12)
   at emitTwo (events.js:106:13)
   at ChildProcess.emit (events.js:191:7)
   at maybeClose (internal/child_process.js:850:16)
   at Socket.<anonymous> (internal/child_process.js:323:11)
   at emitOne (events.js:96:13)
   at Socket.emit (events.js:188:7)
   at Pipe._handle.close [as _onclose] (net.js:492:12)
```

**Comment by hdgarrood** [comment]
It seems like `psvm current` just delegates to `psc --version`, i.e. uses whatever version of psc you have on your path. I would personally expect `psvm current` to give you the result of `$HOME/.psvm/current/vim/psc --version`, i.e. whichever version of `psc` that `psvm` considers current. I think the current behaviour might be a bit confusing if users have other `psc` executables elsewhere on their PATH.
